# Generated by Django 5.2.3 on 2025-06-23 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_walker_options'),
        ('users', '0005_review_walker_alter_review_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('site', 'Отзыв о сайте'), ('walker', 'Отзыв о выгульщике')], default='site', max_length=10, verbose_name='Тип отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='walker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='walker_reviews', to='services.walker'),
        ),
    ]
