# Generated by Django 5.1.7 on 2025-06-12 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название региона')),
                ('latitude', models.FloatField(verbose_name='Широта центра региона')),
                ('longitude', models.FloatField(verbose_name='Долгота центра региона')),
            ],
        ),
        migrations.CreateModel(
            name='PetFriendlyPlaceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название места')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('photo', models.ImageField(upload_to='place_photos/', verbose_name='Фото места')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpzona.region', verbose_name='Регион')),
            ],
        ),
        migrations.CreateModel(
            name='PetFriendlyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approved_place', to='wpzona.petfriendlyplacesubmission', verbose_name='Заявка')),
            ],
        ),
    ]
