# Generated by Django 5.1.7 on 2025-06-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpzona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
