# Generated by Django 5.1.7 on 2025-06-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_services_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя выгульщика')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('image', models.ImageField(blank=True, null=True, upload_to='walkers_media', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='О себе')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Опыт работы (лет)')),
                ('rating', models.FloatField(default=5.0, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Выгульщик',
                'verbose_name_plural': 'Выгульщики',
            },
        ),
        migrations.AddField(
            model_name='servicescategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories_media', verbose_name='Изображение категории'),
        ),
        migrations.AddField(
            model_name='servicescategory',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='URL-адрес'),
            preserve_default=False,
        ),
    ]
