# Generated by Django 5.1.7 on 2025-06-15 18:05

from django.db import migrations
import django.utils.text


def update_slugs(apps, schema_editor):
    ServicesCategory = apps.get_model('services', 'ServicesCategory')
    for category in ServicesCategory.objects.all():
        category.slug = django.utils.text.slugify(category.name)
        category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_walker_servicescategory_image_servicescategory_slug'),
    ]

    operations = [
        migrations.RunPython(update_slugs),
    ]
