# Generated by Django 5.2.3 on 2025-06-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_walker_status_walker_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walker',
            options={},
        ),
    ]
